BTCUSDT:USDT:
  atr_period: 14
  avg_loss_pct: 0.09150000000000001
  avg_win_pct: 0.12685000000000002
  base_position_size: 1000.0
  calibration_sample_size: 3
  confidence_score: 0.5823
  cost_weight: 1.0
  ema_long: 200
  ema_short: 50
  flow_weight: 1.0
  info_weight: 1.0
  kelly_fraction: 0.25
  last_updated: 1756920763.393285
  max_drawdown: 0.0
  max_position_size: 5000.0
  max_spread_bps: 15.0
  min_atr_pct: 0.001
  min_depth_usd: 25000.0
  risk_multiplier: 1.0
  rsi_period: 14
  sharpe_ratio: 0.0
  total_trades: 3
  vol_weight: 1.0
  win_rate: 0.5455000000000001
ETHUSDT:USDT:
  atr_period: 14
  avg_loss_pct: 0.0922
  avg_win_pct: 0.1368
  base_position_size: 1000.0
  calibration_sample_size: 2
  confidence_score: 0.51
  cost_weight: 1.0
  ema_long: 200
  ema_short: 50
  flow_weight: 1.0
  info_weight: 1.0
  kelly_fraction: 0.25
  last_updated: 1756920763.393297
  max_drawdown: 0.0
  max_position_size: 5000.0
  max_spread_bps: 15.0
  min_atr_pct: 0.001
  min_depth_usd: 25000.0
  risk_multiplier: 1.0
  rsi_period: 14
  sharpe_ratio: 0.0
  total_trades: 2
  vol_weight: 1.0
  win_rate: 0.505
SOLUSDT:USDT:
  atr_period: 14
  avg_loss_pct: 0.09310000000000002
  avg_win_pct: 0.1395
  base_position_size: 1000.0
  calibration_sample_size: 2
  confidence_score: 0.508
  cost_weight: 1.0
  ema_long: 200
  ema_short: 50
  flow_weight: 1.0
  info_weight: 1.0
  kelly_fraction: 0.25
  last_updated: 1756920763.393307
  max_drawdown: 0.0
  max_position_size: 5000.0
  max_spread_bps: 15.0
  min_atr_pct: 0.001
  min_depth_usd: 25000.0
  risk_multiplier: 1.0
  rsi_period: 14
  sharpe_ratio: 0.0
  total_trades: 2
  vol_weight: 1.0
  win_rate: 0.49500000000000005
